select * from customer_retention limit 20

--Q1.Which customers have completed the highest number of rides?

SELECT customer_id,
COUNT(booking_id) AS completed_rides
FROM customer_retention
WHERE booking_status = 'Completed'
GROUP BY customer_id
ORDER BY completed_rides DESC;

--Q2.What is the total booking value generated by each customer?

SELECT customer_id,
SUM(booking_value) AS total_revenue
FROM customer_retention
WHERE booking_status = 'Completed'
GROUP BY customer_id
ORDER BY total_revenue DESC;

--Q3.Which vehicle type is booked the most?

SELECT vehicle_type,
COUNT(booking_id) AS total_bookings
FROM customer_retention
GROUP BY vehicle_type
ORDER BY total_bookings DESC

--Q4.Which pickup locations have the highest number of completed rides?

SELECT pickup_location,
COUNT(booking_id) AS completed_rides
FROM customer_retention
WHERE booking_status = 'Completed'
GROUP BY pickup_location
ORDER BY completed_rides DESC;

--Q5.Which customers cancelled the highest number of rides?

SELECT customer_id,
COUNT(booking_id) AS cancelled_rides
FROM customer_retention
WHERE booking_status = 'Cancelled by Customer'
GROUP BY customer_id
ORDER BY cancelled_rides DESC;

--Q6.What is the average booking value for each payment method?

SELECT
    payment_method,
    ROUND(AVG(booking_value::numeric), 2) AS average_booking_value
FROM customer_retention
WHERE booking_status = 'Completed'
GROUP BY payment_method
ORDER BY average_booking_value DESC;

--Q7.Which vehicle type has the highest average customer rating?

SELECT
    vehicle_type,
    ROUND(AVG(customer_rating::numeric), 2) AS average_customer_rating
FROM customer_retention
WHERE booking_status = 'Completed'
GROUP BY vehicle_type
ORDER BY average_customer_rating DESC;

--Q8.Which customers have used more than one payment method?

SELECT
    customer_id,
    COUNT(DISTINCT payment_method) AS payment_methods_used
FROM customer_retention
GROUP BY customer_id
HAVING COUNT(DISTINCT payment_method) > 1
ORDER BY payment_methods_used DESC;

--Q9.Compare the average waiting time (VTAT & CTAT) for completed rides and cancelled rides?

SELECT
    booking_status,
    ROUND(AVG(avg_vtat::numeric), 2) AS average_vtat,
    ROUND(AVG(avg_ctat::numeric), 2) AS average_ctat
FROM customer_retention
GROUP BY booking_status
ORDER BY average_vtat DESC;

--Q10.Which customers have both the highest booking frequency and the highest total booking value?

SELECT
    customer_id,
    COUNT(booking_id) AS total_bookings,
    SUM(booking_value) AS total_booking_value
FROM customer_retention
WHERE booking_status = 'Completed'
GROUP BY customer_id
ORDER BY total_bookings DESC,
         total_booking_value DESC;
